name: Deploy TSX Project via FTPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Build project
      - name: Build project
        run: |
          npm ci
          npm run build

      # 3. Deploy via FTPS (explicit TLS)
      - name: Deploy to SuperHosting via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.websaitovete.eu
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./dist/
          server-dir: /home/websuarl/appnails
          security: loose
          timeout: 60000
