name: Deploy TSX Project via SFTP

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build project
      - name: Build project
        run: |
          npm install
          npm run build

      # 3. Deploy via SFTP
      - name: Deploy to SuperHosting via SFTP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 1022
          protocol: sftp
          source: "dist/"
          target: "/public_html/"
          rm: true
