name: Deploy TSX Project via FTPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build project
      - name: Build project
        run: |
          npm install
          npm run build

      # 3. Deploy via FTPS
      - name: Deploy to SuperHosting via FTPS
        uses: jakejarvis/ftp-deploy@v1
        with:
          server: ${{ secrets.FTPS_HOST }}
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          port: ${{ secrets.FTPS_PORT }}
          local-dir: ./dist
          server-dir: /public_html
          protocol: ftps
          secure: true       # Use explicit FTP over TLS
          passive: true      # Recommended for FTPS
          parallel: 4
