name: Deploy TSX Project via SFTP

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install dependencies and build
      - name: Build project
        run: |
          npm install
          npm run build

      # 3. Deploy via SFTP
      - name: Deploy to SuperHosting via SFTP
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "dist/"
          target: "/public_html/"
          rm: true          # remove existing files before upload
          recursive: true   # upload folder contents recursively
